version: "3.9"
services:
  base-datos-app-web:
    image: mysql:5.7.26
    ports:
      - ${PUERTO_DB}:3306
    networks: #red para conectar los equipos.
      - red-app
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_USER=$DB_USER
      - MYSQL_DATABASE=$DB_NAME
    volumes: #volumen de datos utilizado.
      - ~/dato_mysql_compose:/var/lib/mysql
  redis:
    image: "redis:alpine"
    hostname: $REDIS_HOST
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    networks: #red para conectar los equipos.
      - red-app
  app1:
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    ports: #puertos que estaran expuestos.
      - ${PUERTO_APP1}:${PUERTO_APP1}
    networks: #red para conectar los equipos.
      - red-app
    command: bash -c "java -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar --server.port=$PUERTO_APP1 --spring.session.store-type=redis --spring.session.redis.flush-mode=on_save --spring.redis.host=$REDIS_HOST --spring.redis.port=$REDIS_PORT"
  app2:
    build: .
    depends_on:
      - app1
    env_file:
      - .env
    ports: #puertos que estaran expuestos.
      - ${PUERTO_APP2}:${PUERTO_APP2}
    networks: #red para conectar los equipos.
      - red-app
    command: bash -c "java -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar --server.port=$PUERTO_APP2 --spring.session.store-type=redis --spring.session.redis.flush-mode=on_save --spring.redis.host=$REDIS_HOST --spring.redis.port=$REDIS_PORT"
  app3:
    build: .
    depends_on:
      - app2
    env_file:
      - .env
    ports: #puertos que estaran expuestos.
      - ${PUERTO_APP3}:${PUERTO_APP3}
    networks: #red para conectar los equipos.
      - red-app
    command: bash -c "java -Djava.security.egd=file:/dev/./urandom -jar /app/app.jar --server.port=$PUERTO_APP3 --spring.session.store-type=redis --spring.session.redis.flush-mode=on_save --spring.redis.host=$REDIS_HOST --spring.redis.port=$REDIS_PORT"
  haproxy:
    build: ./haproxy/
    depends_on:
      - app3
    env_file:
     - .env
    ports:
      - "80:80"
      - "443:443"
    networks: #red para conectar los equipos.
      - red-app
networks:  #bloque para las redes
  red-app:   #indicando la red definida
volumes: #Bloque para definir los volumenes
  mi-volumen-compose:
