#indica la version de Docker Compose utilizada
version: '3.8'
#Bloque de servicios, indica los contenedores a utilizar.
services:
  app1: #  #nombre del servicio
    #image: ${DK_USR}/practica4 #imagen utilizada si viene del registro.
    build: .
    ports: #puertos que estaran expuestos.
      - ${PUERTO_APP1}:${PUERTO_APP1}
    env_file:
      - .env
    environment: #variable de ambiente
      - NOMBRE_APP=$AMBIENTE
    networks: #red para conectar los equipos.
      - red-app
    volumes:
      - mi-volumen-compose:/tmp/
    depends_on: #indica que primero debe subir los servicios indicados.
      - base-datos-app-web
    command: bash -c "cd /app && java -jar practica5-0.0.1-SNAPSHOT.jar --server.port=8080"
  app2: #  #nombre del servicio
    #image: ${DK_USR}/practica4 #imagen utilizada si viene del registro.
    build: .
    ports: #puertos que estaran expuestos.
      - ${PUERTO_APP2}:${PUERTO_APP2}
    env_file:
      - .env
    environment: #variable de ambiente
      - NOMBRE_APP=$AMBIENTE
    networks: #red para conectar los equipos.
      - red-app
    volumes:
      - mi-volumen-compose:/tmp/
    depends_on: #indica que primero debe subir los servicios indicados.
      - base-datos-app-web
    command: bash -c "cd /app && java -jar practica5-0.0.1-SNAPSHOT.jar --server.port=8081"
  app3: #  #nombre del servicio
    #image: ${DK_USR}/practica4 #imagen utilizada si viene del registro.
    build: .
    ports: #puertos que estaran expuestos.
      - ${PUERTO_APP3}:${PUERTO_APP3}
    env_file:
      - .env
    environment: #variable de ambiente
      - NOMBRE_APP=$AMBIENTE
    networks: #red para conectar los equipos.
      - red-app
    volumes:
      - mi-volumen-compose:/tmp/
    depends_on: #indica que primero debe subir los servicios indicados.
      - base-datos-app-web
    command: bash -c "cd /app && java -jar practica5-0.0.1-SNAPSHOT.jar --server.port=8082"

  haproxy:
    build: ./haproxy/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app3
    

  base-datos-app-web:
    image: mysql:5.7.26
    ports:
      - ${PUERTO_DB}:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_USER=$DB_USER
      - MYSQL_DATABASE=$DB_NAME
    volumes:   #volumen de datos utilizado.
      - ~/dato_mysql_compose:/var/lib/mysql
    networks:
      - red-app

networks:  #bloque para las redes
  red-app:   #indicando la red definida

volumes: #Bloque para definir los volumenes
  mi-volumen-compose:
